version: "3.8"
services:
  app:
    build: .
    image: my_fast_api:latest
    container_name: myFastApi
    volumes:
      - /home/elianrenteria/photos:/app/photos
      - /home/elianrenteria:/app/static
    networks:
      - shared-network
    restart: always

networks:
  shared-network:
    external: true